version: '3.1'

services:
  test:
    image: test
    build:
      context: .
      dockerfile: IntegrationTestsDockerfile
    depends_on:
      - webapi
  webapi:
    image: webapi
    ports:
        - "8001:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Your_password123