version: "3.8"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes: 
            - sqlvolume:/var/opt/mssql 
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
volumes:
  sqlvolume: